modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/FrostedHeart/issues"
[[mods]] #mandatory
modId = "frostedheart" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "The Winter Rescue: Frosted Heart" #mandatory
authors = "Developed by TeamMoeg, with the help of many contributors. See description below."
description = '''
The Core Mod for The Winter Rescue Modpack.

 (In the order of first joining, not contribution size. 按加入时间，而非贡献大小排序。)

Development Team 开发团队 (www.teammoeg.com):
- Progamming 编程: YueSha, khjxiaogu, duck_egg, dashuaibia, goumo_g, yuqijun, zombie_cute
- Art 美术: Lyuuke, gomou_g, Dsanilin
- Building 建筑: Fu_Yang, OEIIO, Lanshan
- Design 设计: YueSha, duck_egg, dashuaibia, khjxiaogu, Lyuuke, alphaGem, JackyWangMislantiaJnirvana
- Writing 写作: YueSha, Lanshan
- Quality Assurance 质量保证: asdfghjkl, shidi
- Operation 运营: Evan, YueSha, khjxiaogu

Localization 本地化:
- Chinese: TeamMoeg
- English: TeamMoeg, Jerzerak, AGmouse, sayyidyofa, alyashour, collin-marando
- Russian: Whitealbum0, EvilToasterDBU

Contributors 贡献者:
- Programming 编程: LetterN, Huaji_Qinmi, ceary741, Gugusb, Winged-Hussars, ewoudje, IBlessus
- Art 美术: Heitao
- Building 建筑: nekocrane, GuardianWorld, Keisari
- Writing 写作: ZXCZST

Special Thanks 特别感谢:
- OpenGameArt (opengameart.org) for sound effects.
- Matthew Pablo (www.matthewpablo.com) for music.
- DALL-E (openai.com) for the opening CG art.
- The TeamMoeg Community (www.teammoeg.com) for support and feedback.
- The NeoForge Team for the modding platform.
- The Mojang Team for the game itself.

Supporters 赞助者:
爱发电用户_EYjb
爱发电用户_db412
爱发电用户_db412
苏情
爱发电用户_5YNW
爱发电用户_e22a0
Bob
久侘歌
爱发电用户_QFTp
雾散就恋爱.
Ericaaaditor
蓝闪
Jfish
玫瑰
星海无妄
狗头人
米子弟
爱发电用户_2035d
devil_tiga
爱发电用户_ca193
爱发电用户_RQMm
新疆第一深情
蓝闪
爱发电用户_cc1b7
Zigned
dye
bosszeng
爱发电用户_d9f24
林晨有北
1313
xiaoliyuwang
金广源大图标书广告  18995128070
爱发电用户_b142e
爱发电用户_Xens
JhCiowsd
不听话的小孩会被断网
Trilonites
爱发电用户_b7c89
クう
爱发电用户_mcAP
爱发电用户_b7c71
淞沐丶溟
爱发电用户_eXYh
大魔王
爱发电用户_sat3
Absolute_Radiance
陌
Tiandi
南鸳
魔
Lilliavlia
爱发电用户_9rhS
不会飞的麻将
爱发电用户_jWAs
Mango04a
冰折扇
xzh1809
彦祖
晓云Orins
堑渊
逍遥游梦狼
逍遥游梦狼
星海无妄
晴枫
爱发电用户_a19d3
香蕉吃NaNa
爱发电用户_965b4
爱发电用户_26640
橙子
Rhein_Dreammer
w299
电狐3
爱发电用户_65c67
爱发电用户_b5b60
浣熊科学
爱发电用户_5wUy
爱发电用户_S7Vn
guang
Lyxanoo梦
NaCl_233
zui_ai_lei_mu
樱花庄の酪祺
爱发电用户_9b761
zhay_y
爱发电用户_8cd15
爱发电用户_8cd15
winnt
爱发电用户_RDYc
一只鱼人
COcoa
海鲜
爱发电用户_MQuA
爱发电用户_e6Uj
raiptor
拾玖
拾玖
raven99856
小威sir
C_urse
爱发电用户_fd9c3
爱发电用户_f22dd
YuXian
臦
爱发电用户_R3Qu
无相炎王
无相炎王
爱发电用户_WB7R
渡鸦远行
爱发电用户_NpHY
酷哥
爱发电用户_HPNt
爱发电用户_4862b
爱发电用户_bdec5
爱发电用户_519ae
爱发电用户_519ae
爱发电用户_3fc91
qwed
爱发电用户_82422
爱发电用户_b1f0c
爱发电用户_e611e
ChinaMCAX
ChinaMCAX
爱发电用户_c75db
小轩
Eills Zhang
爱发电用户_a678c
爱发电用户_cWSR
爱发电用户_81969
爱发电用户_KYqS
佛伦sama
爱发电用户_4df47
爱发电用户_EkRG
爱发癫用户（bushi）
漫天yyyy
小瑞
高庄主
小铃铛
He91105
.
ZY
笑柒XIAO_Q7
辛久
七煞冰魂
爱发电用户_df85
爱发电用户_74HQ
Fardi
爱发电用户_Sy6H
爱发电用户_4c33c
爱发电用户_jUbq
大圣兽-凌云
爱发电用户_uw9T
爱发电用户_0abfb
爱发电用户_Dgxp
爱发电用户_hmF4
寻梦
爱发电用户_bKCf
爱发电用户_UpRy
一个仙人球
kater
爱发电用户_2b657
loki
爱发电用户_Ehrq
罗二妹
大圣兽-凌云
爱发电用户_b3908
爱发电用户_36a14
RE_
爱发电用户_eQJg
只是来打酱油的
爱发电用户_tsvE
爱发电用户_QaPA
喜饮冻柠茶?
爱发电用户_4nmX
白鬼院凛凛蝶
白鬼院凛凛蝶
zhipr
爱发电用户_3aE4
Copper_Sulfate
回忆East
爱发电用户_X4uF
王副主席
TheChans
爱发电用户_YtM6
爱发电用户_e5e9d
爱发电用户_KerE
爱发电用户_6efb2
爱发电用户_Qb3U
zx120q
爱发电用户_pRtc
fw丶抠脚
катюша
CN_ChiTu
爱发电用户_4bc6f
钱大吉
爱发电用户_hb6v
Stupid_Fly
cappi
月影黯然
打酱铀的
老衲法号方丈
Viva_Hurry
RE_
爱发电用户_1b08b
爱发电用户_Mbwy
微笑
爱发电用户_dGmv
Aoetonu
鲨霖雨
鲨霖雨
双轨并行
铁球qwq
沐陵仙君
xuwuwudi
Xross
Aback111
Carl Yu
叁无樱
爱发电用户_fXsH
Wukim-Rim
06431s
爱发电用户_9b1a9
沐休
漂流的二次元
爱发电用户_cxE6
爱发电用户_2e8d9
GBD
柚叽
三月
爱发电用户_84bd4
缘起缘生
gritting
爱发电用户_ve6u
宏楼 Koiro
爱发电用户_tCMB
爱发电用户_cc101
爱发电用户_CUEK
霵擰瑰緒
ykqqq
爱发电用户_e45e8
卿舵主
vvc
已注销
莫随流年
78p123
爱发电用户_32274
爱发电用户_wnTD
爱发电用户_7ef87
Similtrack
爱发电用户_BSxQ
伯溪
顾熙豪
顾熙豪
-公式呵呵-
-公式呵呵-
ToveR
一玮大人
Totoro的小龙猫
Totoro的小龙猫
玩塔罗牌的猫
猫蜀黍
冬日落叶
爱发电用户_c0e1d
青木
柯白
VM汉化组
VM汉化组
东皇钟
TiCl4
Rainbow
爱发电用户_71585
爱发电用户_rCP4
巫妖菲涅普
大砍刀从来不乱说话
爱发电用户_YXmq
woyun
KevinRay
无珠
PenguinSAMA
Luyen
顾逸宝
zkhsrc
爱发电用户_31db0
乄羽空丶
幻想星墨
爱发电用户_0b813
Academic_Sanctum
睡午觉
爱发电用户_7a404
爱发电用户_e3925
alfie_zh
cccca
modular
涩桉
hzic
Thresh_M
爱发电用户_JWDC
爱发电用户_a6a9a
gaogao_qwq
爱发电用户_4c9b6
gaogao_qwq
爱发电用户_Agwk
爱发电用户_e5a3a
爱发电用户_fe7ab
爱发电用户_a6a9a
爱发电用户_e5a3a
爱发电用户_B7af
LittleAK
爱发电用户_28640
爱发电用户_d8624
爱发电用户_AVFb
Hongchafang
Luyen
幻想星墨
枫庭
爱发电用户_de3ba
ifuan
爱发电用户_fa4e6
爱发电用户_eebbe
爱发电用户_7a404
琅樊古代
琅樊古代
无珠
爱发电用户_PR5W
爱发电用户_c5c89
林云曦
无欲乘风
SHIRO
无珠
无珠
无珠
咸鱼老马
离人九歌
爱发电用户_19afa
Lestech233
Fried_ice
爱发电用户_mcAP
小轩
爱发电用户_3cAX
枫庭
史莱姆清风
傻东西
傻东西
爱发电用户_K6c7
爱发电用户_9hdG
爱发电用户_0678a
爱发电用户_0678a
爱发电用户_521dc
爱发电用户_k6jU
sanrenxin
6yyyyy
Anonlement
爱发电用户_TUCR
爱发电用户_w8xs
枫庭
逍遥
剑指孤城
爱发电用户_S5Bm
爱发电用户_dyqA
Sando
爱发电用户_Hxyt
枫庭
柳文罹
Jieice
Emiyashirou
ITRS
枫庭
NbeL
NbeL
落花随水去
GBLodb
絮dx
usain
ucantrt
Evan
冥可玲
卢克儿
爱发电用户_g5DS
爱发电用户_G6gQ
'''
[[dependencies.frostedheart]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedheart]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.4)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedheart]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.20.1-10.1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.j,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.10-7,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="terralith"
    mandatory=false
    versionRange="[2.5.4,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="caupona"
    mandatory=true
    versionRange="[1.20.1-0.4.9,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="crockpot"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="stone_age"
    mandatory=false
    versionRange="[1.4.8,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="charcoal_pit"
    mandatory=false
    versionRange="[3.10,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="curios"
    mandatory=true
    versionRange="[5.9.1+1.20.1,)"
    ordering="BEFORE"
    side="BOTH"

