modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/FrostedHeart/issues"
[[mods]] #mandatory
modId = "frostedheart" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "The Winter Rescue: Frosted Heart" #mandatory
itemIcon="frostedheart:energy_core"
displayURL="https://www.curseforge.com/minecraft/mc-mods/frosted-heart"
logoFile="logo.png"
authors = "Developed by TeamMoeg, with the help of many contributors. See description below."
description = '''
The Core Mod for The Winter Rescue Modpack.

Discord: https://discord.gg/BWn6E94

 (In the order of first joining, not contribution size. 按加入时间，而非贡献大小排序。)

Development Team 开发团队 (www.teammoeg.com):
- Progamming 编程: YueSha, khjxiaogu, duck_egg, dashuaibia, goumo_g, yuqijun
- Art 美术: Lyuuke, gomou_g, Dsanilin
- Building 建筑: Fu_Yang, OEIIO, Lanshan
- Design 设计: YueSha, duck_egg, dashuaibia, khjxiaogu, Lyuuke, alphaGem, JackyWangMislantiaJnirvana
- Writing 写作: YueSha, Lanshan
- Quality Assurance 质量保证: asdfghjkl, shidi
- Operation 运营: Evan, YueSha, khjxiaogu

Localization 本地化:
- Chinese: TeamMoeg
- English: TeamMoeg, Jerzerak, AGmouse, sayyidyofa, alyashour, collin-marando
- Russian: Whitealbum0, EvilToasterDBU

Contributors 贡献者:
- Programming 编程: LetterN, Huaji_Qinmi, ceary741, Gugusb, Winged-Hussars, ewoudje, IBlessus, KilaBash
- Art 美术: Heitao
- Building 建筑: nekocrane, GuardianWorld, Keisari
- Writing 写作: ZXCZST

Special Thanks 特别感谢:
- alcatraz (github.com/alcatrazEscapee) for Primal Winter inspiration.
- OpenGameArt (opengameart.org) for sound effects.
- Matthew Pablo (www.matthewpablo.com) for music.
- DALL-E (openai.com) for the opening CG art.
- The TeamMoeg Community (www.teammoeg.com) for support and feedback.
- The NeoForge Team for the modding platform.
- The Mojang Team for the game itself.

Supporters 赞助者:
See our official website.
'''
[[dependencies.frostedheart]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedheart]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.4)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedheart]]
    modId="chorda"
    mandatory=true
    versionRange="[0.1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.20.1-10.1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.j,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.10-7,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="terralith"
    mandatory=false
    versionRange="[2.5.4,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="caupona"
    mandatory=false
    versionRange="[1.20.1-0.4.9,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="crockpot"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="stone_age"
    mandatory=false
    versionRange="[1.4.8,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="charcoal_pit"
    mandatory=false
    versionRange="[3.10,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="curios"
    mandatory=true
    versionRange="[5.9.1+1.20.1,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedheart]]
    modId="tetra"
    mandatory=false
    versionRange="[6.6.0,)"
    ordering="BEFORE"
    side="BOTH"


[[mods]] #mandatory
modId = "chorda" #mandatory
version = "0.1.0" #mandatory
displayName = "Chorda" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/chorda"
logoFile="logo.png"
authors = "Developed by TeamMoeg, with the help of many contributors. See description below."
description = '''
The Library Mod for TeamMoeg Projects.
'''
[[dependencies.chorda]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.chorda]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.4)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.chorda]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[1.20.1-10.1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.chorda]]
    modId="create"
    mandatory=false
    versionRange="[0.5.1.j,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.chorda]]
    modId="flywheel"
    mandatory=false
    versionRange="[0.6.10-7,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.chorda]]
    modId="curios"
    mandatory=false
    versionRange="[5.9.1+1.20.1,)"
    ordering="BEFORE"
    side="BOTH"
[[mods]] #mandatory
modId = "frostedresearch" #mandatory
version = "0.1.0" #mandatory
displayName = "Frosted Research" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/frostedresearch"
logoFile="logo.png"
authors = "Developed by TeamMoeg, with the help of many contributors."
description = '''
The research mod originally created for The Winter Rescue.
'''
[[dependencies.frostedresearch]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedresearch]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.4)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.frostedresearch]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[1.20.1-10.1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedresearch]]
    modId="create"
    mandatory=false
    versionRange="[0.5.1.j,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedresearch]]
    modId="flywheel"
    mandatory=false
    versionRange="[0.6.10-7,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.frostedresearch]]
    modId="chorda"
    mandatory=true
    versionRange="[0.1,0.2)"
    ordering="BEFORE"
    side="BOTH"